### ISSUE TITLE
Minitest/LiteralAsActualArgument cop error

### ISSUE THREAD

**Issue by TSMMark** [rubocop-hq/rubocop-minitest#101]
> An error occurred while Minitest/LiteralAsActualArgument cop was inspecting XXXXXXXX:65.

On that line is:

```ruby
assert_equal releases_count, form.all_releases_dataset.all.size
```

Other lines that cause error this include:

```ruby
assert_equal(*channels_normal_attrs)
assert_equal current_path, "/releases/distribute"
# and several more, but all of them in my case either splat args, or omit parens.
```

--------

## Expected behavior

Should not error when parsing.

## Actual behavior

Errors when parsing.

## Steps to reproduce the problem

I'm guessing it could be repro'd in a test here https://github.com/rubocop-hq/rubocop-minitest/blob/master/test/rubocop/cop/minitest/literal_as_actual_argument_test.rb

I will try to repro in a test next if I have time.

## RuboCop version

```
bash-5.0# bundle exec rubocop -V
0.87.1 (using Parser 2.7.1.4, rubocop-ast 0.1.0, running on ruby 2.5.3 x86_64-linux-musl)
```

**Comment by TSMMark** [comment]
@fatkodima FYI see above. I'll try to repro ASAP

**Comment by TSMMark** [comment]
@fatkodima I got a simple repro in this commit in `test/rubocop/cop/minitest/literal_as_actual_argument_test.rb` 

https://github.com/rubocop-hq/rubocop-minitest/commit/3ebd09736b84a798bffa16551ea3bcedf26bcf13

```
  1) Error:
LiteralAsActualArgumentTest#test_does_not_register_offense_when_parens_omitted:
NoMethodError: undefined method `end' for nil:NilClass
    /Users/mark/code/rubocop-minitest/lib/rubocop/cop/minitest/literal_as_actual_argument.rb:43:in `arguments_range'
    /Users/mark/code/rubocop-minitest/lib/rubocop/cop/minitest/literal_as_actual_argument.rb:27:in `on_send'
    /Users/mark/.rvm/gems/ruby-2.5.5/bundler/gems/rubocop-e80b2782b422/lib/rubocop/cop/commissioner.rb:91:in `block (2 levels) in trigger_responding_cops'
    /Users/mark/.rvm/gems/ruby-2.5.5/bundler/gems/rubocop-e80b2782b422/lib/rubocop/cop/commissioner.rb:113:in `with_cop_error_handling'
    /Users/mark/.rvm/gems/ruby-2.5.5/bundler/gems/rubocop-e80b2782b422/lib/rubocop/cop/commissioner.rb:90:in `block in trigger_responding_cops'
    /Users/mark/.rvm/gems/ruby-2.5.5/bundler/gems/rubocop-e80b2782b422/lib/rubocop/cop/commissioner.rb:89:in `each'
    /Users/mark/.rvm/gems/ruby-2.5.5/bundler/gems/rubocop-e80b2782b422/lib/rubocop/cop/commissioner.rb:89:in `trigger_responding_cops'
    /Users/mark/.rvm/gems/ruby-2.5.5/bundler/gems/rubocop-e80b2782b422/lib/rubocop/cop/commissioner.rb:61:in `block (2 levels) in <class:Commissioner>'
    /Users/mark/.rvm/gems/ruby-2.5.5/gems/rubocop-ast-0.1.0/lib/rubocop/ast/traversal.rb:109:in `on_def'
    /Users/mark/.rvm/gems/ruby-2.5.5/bundler/gems/rubocop-e80b2782b422/lib/rubocop/cop/commissioner.rb:62:in `block (2 levels) in <class:Commissioner>'
    /Users/mark/.rvm/gems/ruby-2.5.5/gems/rubocop-ast-0.1.0/lib/rubocop/ast/traversal.rb:101:in `on_class'
    /Users/mark/.rvm/gems/ruby-2.5.5/bundler/gems/rubocop-e80b2782b422/lib/rubocop/cop/commissioner.rb:62:in `block (2 levels) in <class:Commissioner>'
    /Users/mark/.rvm/gems/ruby-2.5.5/gems/rubocop-ast-0.1.0/lib/rubocop/ast/traversal.rb:14:in `walk'
    /Users/mark/.rvm/gems/ruby-2.5.5/bundler/gems/rubocop-e80b2782b422/lib/rubocop/cop/commissioner.rb:74:in `investigate'
    /Users/mark/code/rubocop-minitest/test/assertion_helper.rb:74:in `investigate'
    /Users/mark/code/rubocop-minitest/test/assertion_helper.rb:61:in `inspect_source'
    /Users/mark/code/rubocop-minitest/test/assertion_helper.rb:19:in `assert_no_offenses'
    /Users/mark/code/rubocop-minitest/test/rubocop/cop/minitest/literal_as_actual_argument_test.rb:65:in `test_does_not_register_offense_when_parens_omitted'

  2) Error:
LiteralAsActualArgumentTest#test_does_not_register_offense_when_given_splat:
NoMethodError: undefined method `recursive_basic_literal?' for nil:NilClass
    /Users/mark/code/rubocop-minitest/lib/rubocop/cop/minitest/literal_as_actual_argument.rb:28:in `on_send'
    /Users/mark/.rvm/gems/ruby-2.5.5/bundler/gems/rubocop-e80b2782b422/lib/rubocop/cop/commissioner.rb:91:in `block (2 levels) in trigger_responding_cops'
    /Users/mark/.rvm/gems/ruby-2.5.5/bundler/gems/rubocop-e80b2782b422/lib/rubocop/cop/commissioner.rb:113:in `with_cop_error_handling'
    /Users/mark/.rvm/gems/ruby-2.5.5/bundler/gems/rubocop-e80b2782b422/lib/rubocop/cop/commissioner.rb:90:in `block in trigger_responding_cops'
    /Users/mark/.rvm/gems/ruby-2.5.5/bundler/gems/rubocop-e80b2782b422/lib/rubocop/cop/commissioner.rb:89:in `each'
    /Users/mark/.rvm/gems/ruby-2.5.5/bundler/gems/rubocop-e80b2782b422/lib/rubocop/cop/commissioner.rb:89:in `trigger_responding_cops'
    /Users/mark/.rvm/gems/ruby-2.5.5/bundler/gems/rubocop-e80b2782b422/lib/rubocop/cop/commissioner.rb:61:in `block (2 levels) in <class:Commissioner>'
    /Users/mark/.rvm/gems/ruby-2.5.5/gems/rubocop-ast-0.1.0/lib/rubocop/ast/traversal.rb:109:in `on_def'
    /Users/mark/.rvm/gems/ruby-2.5.5/bundler/gems/rubocop-e80b2782b422/lib/rubocop/cop/commissioner.rb:62:in `block (2 levels) in <class:Commissioner>'
    /Users/mark/.rvm/gems/ruby-2.5.5/gems/rubocop-ast-0.1.0/lib/rubocop/ast/traversal.rb:101:in `on_class'
    /Users/mark/.rvm/gems/ruby-2.5.5/bundler/gems/rubocop-e80b2782b422/lib/rubocop/cop/commissioner.rb:62:in `block (2 levels) in <class:Commissioner>'
    /Users/mark/.rvm/gems/ruby-2.5.5/gems/rubocop-ast-0.1.0/lib/rubocop/ast/traversal.rb:14:in `walk'
    /Users/mark/.rvm/gems/ruby-2.5.5/bundler/gems/rubocop-e80b2782b422/lib/rubocop/cop/commissioner.rb:74:in `investigate'
    /Users/mark/code/rubocop-minitest/test/assertion_helper.rb:74:in `investigate'
    /Users/mark/code/rubocop-minitest/test/assertion_helper.rb:61:in `inspect_source'
    /Users/mark/code/rubocop-minitest/test/assertion_helper.rb:19:in `assert_no_offenses'
    /Users/mark/code/rubocop-minitest/test/rubocop/cop/minitest/literal_as_actual_argument_test.rb:75:in `test_does_not_register_offense_when_given_splat'
```

**Comment by TSMMark** [comment]
I'll try fixing it but I'm a Rubocop source novice, will do my best.

**Comment by TSMMark** [comment]
@koic PTAL #102
